name: deploy storybook
on:
  push:
    branches: [main]
    paths:
      - frontend
      - .github/workflows/main.yml
  pull_request:
    paths:
      - frontend
      - .github/workflows/main.yml
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.15.1
      - name: Install Dependencies
        run: npm ci
      - name: Build storybook
        run: npm run build-storybook
      - name: set upload destination directory name
        run: |
          DEST_DIR=${{ github.event.pull_request.number }}
          [ -z $DEST_DIR ] && DEST_DIR=main
          echo "DEST_DIR=${DEST_DIR}" >> $GITHUB_ENV
      - name: upload storybook-static
        run: |
          aws s3 cp --recursive \
            ./storybook-static \
            s3://${{ secrets.BUCKET_NAME }}/storybook/${DEST_DIR}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
