name: remove old storybook
on:
  pull_request:
    types: [closed]
    paths:
      - frontend
      - .github/workflows/main.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: remove storybook-static
        run: |
          DEST_DIR=${{ github.event.pull_request.number }}
          aws s3 rm --recursive \
            s3://${{ secrets.BUCKET_NAME }}/storybook/${DEST_DIR}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
